###
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-brice
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: podinfo-brice


